import type { Metadata } from "next";
import Image from "next/image";
import { SectionIntro } from "@/components/home/SectionIntro";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { CapabilityPill } from "@/components/ui/CapabilityPill";
import { FeatureCard } from "@/components/ui/FeatureCard";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { investorsPageContent as content } from "@/content/pages/investors";

export const metadata: Metadata = { title: "Investors", description: "A public strategic overview of the FARMCLUB OS platform-led agricultural enterprise thesis." };

export default function InvestorsPage() {
  return (
    <>
      <section className="bg-farm-green-950 text-white"><div className="site-container grid min-h-[calc(100svh-5rem)] gap-10 py-12 lg:grid-cols-[1fr_0.86fr] lg:items-center">
        <div><SectionLabel tone="dark">{content.hero.eyebrow}</SectionLabel><h1 className="mt-5 text-4xl font-semibold leading-[1.04] sm:text-6xl lg:text-7xl">{content.hero.heading}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/74 sm:text-xl">{content.hero.description}</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href={content.hero.primaryAction.href} variant="gold">{content.hero.primaryAction.label}</ButtonLink><ButtonLink href={content.hero.secondaryAction.href} variant="dark">{content.hero.secondaryAction.label}</ButtonLink></div></div>
        <div className="relative min-h-[420px] overflow-hidden rounded-lg lg:min-h-[620px]"><Image src={content.hero.image.src} alt={content.hero.image.alt} fill priority sizes="(min-width: 1024px) 44vw, 100vw" className="object-cover" /><div className="absolute inset-x-0 bottom-0 bg-farm-green-950/90 p-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-farm-gold-400">Public strategic overview</p><p className="mt-2 text-sm leading-6 text-white/72">No projections, terms or confidential investment information are presented.</p></div></div>
      </div></section>
      <section className="section-padding bg-white"><div className="site-container grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionIntro eyebrow={content.opportunity.eyebrow} heading={content.opportunity.heading} /><div><p className="text-lg leading-8 text-farm-muted">{content.opportunity.description}</p><ul className="mt-8 divide-y divide-farm-border border-y border-farm-border">{content.opportunity.tensions.map((item, index) => <li key={item} className="flex gap-4 py-5 font-semibold text-farm-green-950"><span className="text-farm-gold-500">0{index + 1}</span>{item}</li>)}</ul></div></div></section>
      <section id="strategic-thesis" className="section-padding scroll-mt-24 bg-farm-cream-100"><div className="site-container"><SectionIntro eyebrow={content.thesis.eyebrow} heading={content.thesis.heading} description={content.thesis.statement} align="center" /><div className="mt-12 grid gap-4 lg:grid-cols-4">{content.thesis.pillars.map((item) => <FeatureCard key={item.title} {...item} />)}</div></div></section>
      <section className="section-padding bg-white"><div className="site-container grid gap-10 lg:grid-cols-[0.72fr_1.28fr]"><div className="lg:sticky lg:top-28 lg:self-start"><SectionIntro eyebrow={content.model.eyebrow} heading={content.model.heading} description={content.model.description} /></div><div className="relative pl-8"><div className="absolute bottom-0 left-3 top-0 w-px bg-farm-green-700" />{content.model.layers.map((layer, index) => <article key={layer.title} className="relative mb-5 rounded-lg border border-farm-border bg-farm-cream-50 p-7"><span className="absolute -left-[1.75rem] top-8 h-4 w-4 rounded-full border-4 border-white bg-farm-gold-500" /><p className="text-sm font-semibold text-farm-green-700">LAYER 0{index + 1}</p><h3 className="mt-4 text-2xl font-semibold text-farm-green-950">{layer.title}</h3><p className="mt-3 text-sm leading-7 text-farm-muted">{layer.description}</p></article>)}</div></div></section>
      <section className="section-padding bg-farm-green-950 text-white"><div className="site-container"><SectionIntro eyebrow={content.sustainability.eyebrow} heading={content.sustainability.heading} tone="dark" /><div className="mt-12 grid gap-px overflow-hidden border border-white/14 bg-white/14 md:grid-cols-2">{content.sustainability.principles.map((item, index) => <article key={item.title} className="bg-farm-green-950 p-7 sm:p-9"><span className="text-sm font-semibold text-farm-gold-400">0{index + 1}</span><h3 className="mt-8 text-2xl font-semibold">{item.title}</h3><p className="mt-4 text-sm leading-7 text-white/70">{item.description}</p></article>)}</div></div></section>
      <section className="section-padding bg-farm-cream-100"><div className="site-container grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><SectionIntro eyebrow={content.impact.eyebrow} heading={content.impact.heading} description={content.impact.description} /><div className="flex flex-wrap gap-3">{content.impact.areas.map((area) => <CapabilityPill key={area}>{area}</CapabilityPill>)}</div></div></section>
      <section className="section-padding bg-white"><div className="site-container grid gap-12 lg:grid-cols-2"><div><SectionIntro eyebrow={content.governance.eyebrow} heading={content.governance.heading} /><ol className="mt-8 divide-y divide-farm-border border-y border-farm-border">{content.governance.principles.map((item, index) => <li key={item} className="flex gap-4 py-4 text-sm font-semibold leading-6 text-farm-green-950"><span className="text-farm-gold-500">{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ol></div><div><SectionIntro eyebrow={content.collaboration.eyebrow} heading={content.collaboration.heading} /><div className="mt-8 grid gap-3">{content.collaboration.items.map((item) => <FeatureCard key={item.title} {...item} />)}</div></div></div></section>
      <section className="bg-farm-cream-100 py-10"><div className="site-container rounded-lg bg-farm-green-900 p-7 text-white sm:p-10 lg:flex lg:items-end lg:justify-between lg:gap-10"><div className="max-w-3xl"><SectionLabel tone="dark">{content.information.eyebrow}</SectionLabel><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">{content.information.heading}</h2><p className="mt-5 text-base leading-8 text-white/72">{content.information.description}</p></div><div className="mt-7 shrink-0 lg:mt-0"><ButtonLink href={content.information.action.href} variant="gold">{content.information.action.label}</ButtonLink></div></div></section>
    </>
  );
}
