import type { Metadata } from "next";
import Image from "next/image";
import { SectionIntro } from "@/components/home/SectionIntro";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { CapabilityPill } from "@/components/ui/CapabilityPill";
import { CtaBand } from "@/components/ui/CtaBand";
import { FeatureCard } from "@/components/ui/FeatureCard";
import { IconBadge } from "@/components/ui/IconBadge";
import { SectionLabel } from "@/components/ui/SectionLabel";
import { platformPageContent as content } from "@/content/pages/platform";

export const metadata: Metadata = { title: "Platform", description: "Explore the FARMCLUB OS Four Engines and connected agricultural enterprise operating model." };

export default function PlatformPage() {
  return (
    <>
      <section className="overflow-hidden bg-farm-cream-100"><div className="site-container grid min-h-[calc(100svh-5rem)] gap-12 py-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
        <div><SectionLabel>{content.hero.eyebrow}</SectionLabel><h1 className="mt-5 text-4xl font-semibold leading-[1.04] text-farm-green-950 sm:text-6xl lg:text-7xl">{content.hero.heading}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-farm-muted sm:text-xl">{content.hero.description}</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href={content.hero.primaryAction.href}>{content.hero.primaryAction.label}</ButtonLink><ButtonLink href={content.hero.secondaryAction.href} variant="secondary">{content.hero.secondaryAction.label}</ButtonLink></div></div>
        <div className="relative min-h-[480px] lg:min-h-[650px]"><div className="absolute inset-0 overflow-hidden rounded-lg"><Image src={content.hero.image.src} alt={content.hero.image.alt} fill priority sizes="(min-width: 1024px) 52vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-farm-green-950/35" /></div><div className="absolute inset-x-5 bottom-5 grid grid-cols-2 gap-2 sm:inset-x-8 sm:bottom-8">{content.architecture.engines.map((engine) => <div key={engine.title} className="border border-white/20 bg-farm-green-950/88 p-4 text-white backdrop-blur-sm"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-farm-gold-400">{engine.label}</p><p className="mt-2 text-sm font-semibold">{engine.title.replace("FARMCLUB ", "")}</p></div>)}</div></div>
      </div></section>
      <section className="section-padding bg-white"><div className="site-container grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><SectionIntro eyebrow={content.concept.eyebrow} heading={content.concept.heading} /><div><p className="text-lg leading-8 text-farm-muted">{content.concept.description}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{content.concept.principles.map((principle, index) => <li key={principle} className="flex gap-3 border-t border-farm-border pt-4 text-sm font-semibold leading-6 text-farm-green-950"><span className="text-farm-gold-500">0{index + 1}</span>{principle}</li>)}</ul></div></div></section>
      <section id="four-engines" className="section-padding scroll-mt-24 bg-farm-green-950 text-white"><div className="site-container">
        <SectionIntro eyebrow={content.architecture.eyebrow} heading={content.architecture.heading} description={content.architecture.description} align="center" tone="dark" />
        <div className="relative mt-14 lg:grid lg:grid-cols-[1fr_0.66fr_1fr] lg:items-center lg:gap-8"><div className="grid gap-5">{content.architecture.engines.slice(0, 2).map((engine) => <EnginePanel key={engine.title} engine={engine} />)}</div><div className="relative my-8 flex min-h-64 items-center justify-center lg:my-0"><div className="absolute inset-x-0 top-1/2 hidden h-px bg-white/20 lg:block" /><div className="relative z-10 flex aspect-square w-52 flex-col items-center justify-center rounded-full border border-farm-gold-400/60 bg-farm-green-900 p-7 text-center shadow-[0_0_0_14px_rgb(255_255_255_/_4%)]"><IconBadge label={content.architecture.core.title} value="OS" tone="gold" /><h3 className="mt-4 text-2xl font-semibold">{content.architecture.core.title}</h3><p className="mt-3 text-xs leading-5 text-white/70">{content.architecture.core.description}</p></div></div><div className="grid gap-5">{content.architecture.engines.slice(2).map((engine) => <EnginePanel key={engine.title} engine={engine} />)}</div></div>
      </div></section>
      <section className="section-padding bg-farm-cream-100"><div className="site-container"><SectionIntro eyebrow={content.capabilityMap.eyebrow} heading={content.capabilityMap.heading} /><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-farm-border bg-farm-border sm:grid-cols-2 lg:grid-cols-3">{content.capabilityMap.items.map((item) => <article key={item.title} className="bg-white p-7"><span className="text-sm font-semibold text-farm-gold-500">{item.badge}</span><h3 className="mt-8 text-2xl font-semibold text-farm-green-950">{item.title}</h3><p className="mt-3 text-sm leading-7 text-farm-muted">{item.description}</p></article>)}</div></div></section>
      <section className="section-padding bg-white"><div className="site-container"><SectionIntro eyebrow={content.journey.eyebrow} heading={content.journey.heading} description={content.journey.description} /><ol className="mt-12 grid border-l border-farm-green-700 md:grid-cols-3 md:border-l-0 md:border-t">{content.journey.steps.map((step) => <li key={step.title} className="relative px-6 py-7 md:px-5 md:pt-9"><span className="absolute -left-2.5 top-8 h-5 w-5 rounded-full border-4 border-white bg-farm-gold-500 md:-top-2.5 md:left-5" /><span className="text-sm font-semibold text-farm-green-700">{step.badge}</span><h3 className="mt-3 text-xl font-semibold text-farm-green-950">{step.title}</h3><p className="mt-3 text-sm leading-7 text-farm-muted">{step.description}</p></li>)}</ol></div></section>
      <section className="section-padding bg-farm-cream-50"><div className="site-container"><SectionIntro eyebrow={content.useCases.eyebrow} heading={content.useCases.heading} align="center" /><div className="mt-12 grid gap-4 md:grid-cols-2">{content.useCases.items.map((item) => <FeatureCard key={item.title} {...item} />)}</div></div></section>
      <section className="section-padding bg-farm-green-950 text-white"><div className="site-container grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative aspect-[4/3] overflow-hidden rounded-lg"><Image src={content.physicalBridge.image.src} alt={content.physicalBridge.image.alt} fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div><SectionLabel tone="dark">{content.physicalBridge.eyebrow}</SectionLabel><h2 className="mt-4 text-3xl font-semibold sm:text-5xl">{content.physicalBridge.heading}</h2><p className="mt-5 text-lg leading-8 text-white/74">{content.physicalBridge.description}</p><div className="mt-8 flex flex-wrap gap-3">{content.physicalBridge.flow.map((item) => <CapabilityPill key={item} tone="dark">{item}</CapabilityPill>)}</div></div></div></section>
      <CtaBand {...content.cta} />
    </>
  );
}

function EnginePanel({ engine }: { engine: (typeof content.architecture.engines)[number] }) {
  return <article className="dark-panel p-5"><div className="flex items-center gap-4"><IconBadge label={engine.title} value={engine.badge} tone="dark" /><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-farm-gold-400">{engine.label}</p><h3 className="mt-1 text-xl font-semibold">{engine.title}</h3></div></div><p className="mt-4 text-sm leading-7 text-white/72">{engine.description}</p><div className="mt-4 flex flex-wrap gap-2">{engine.supports.map((item) => <CapabilityPill key={item} tone="dark">{item}</CapabilityPill>)}</div></article>;
}
